### ISSUE TITLE
Pixel project matrix not invertible

### ISSUE THREAD

**Issue by luskin** [uber-common/viewport-mercator-project#67]
Some of our customers are receiving the following error, crashing our site: 
<img width="1029" alt="screen shot 2018-04-26 at 10 04 28 am" src="https://user-images.githubusercontent.com/5702322/39320528-41f9d2c6-4939-11e8-83b2-eabc8a4da8e8.png">

I need to understand what would cause this error so that I can make sure to catch it before crashing, thanks.

**Comment by ibgreen** [comment]
@luskin 90 degree pitch would be the main thing I can think of. i.e. looking at the map directly from the side. In that case you might want to avoid 90 and cap at 89 / 91 degrees.

If not that, can you paste the viewport parameters?

**Comment by wentsul** [comment]
@ibgreen we're seeing the following errors in our application as well. Would be possible to add more information to the error message to help understand which part of the viewport state is invalid? Is there a recommended way to handle these types of errors from within a react application (one that uses react-map-gl).

**Comment by ahsanshah** [comment]
Anyone have any update on this. We are using Apache Superset and see this issue when the view is limited to 1-2 points on the map.  How can this be corrected. is it related to data/coordinates or is it a bug?

**Comment by randori-aristides** [comment]
I've hit this in a case where I pass in two identical locations. It should be reproducible by calling fitBounds like -

```javascript
const options = {
  height: 100,
  width:100,
  bearing: 0,
  pitch: 0,
  zoom: 2
}

const viewport = new WebMercatorViewport(oldViewport)
viewport.fitBounds([[-70, 10], [-70, 10]])

// Error: Pixel project matrix not invertible
```

**Comment by uragecz** [comment]
I have same problem.. after rendering cca 100+ location.. i sometimes get this error - `Uncaught Error: Pixel project matrix not invertible ` Any tips what can cause it ?

**Comment by ibgreen** [comment]
Using the same or almost same position for both arguments to `fitBounds` would result in zero `width` and `height`, which would be a plausible reason for a non-invertible matrix. 

Somewhere in the app there needs to be logic to handle this (i.e. specify a minimum radius to cover, and adjust the points accordingly). 

While the minimum area to show is a choice the app needs to make, we could probably provide better support:
* A better error from viewport-mercator-project would be nice.
* Perhaps an additional argument to `fitBounds` that allows the app to specify min width/height?

**Comment by ToddJacobus** [comment]
I'm not sure if this is helpful, but I was encountering this error as well and determined that my default, initial viewport had a width of 0 because I was using a css string "100%" for a default viewport setting in my reducer.  But, initially, the width of the element was 0 when the app booted up, resulting in `Error: Pixel project matrix not invertible`.  I'm new so maybe I'm missing something else here, but I set both the default height and width to `Window.innerHeight` and `Window.innerWidth` respectively, while later updating the viewport width to the "100%" css string using `componentDidMount`, and it works just fine.

Also thanks very much to the devs for the continued support and updates.  I'm loving react-map-gl.
